name: Detect and Encrypt Sensitive Info

on:
  push:
    paths:
      - '**' # Trigger on any file changes
  workflow_dispatch: # Allow manual trigger

jobs:
  detect-sensitive-info:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Scan for sensitive information
    - name: Scan for sensitive information
      uses: github/codeql-action/init@v2
      with:
        languages: javascript
        queries: +security-and-quality
    - name: Perform the scan
      uses: github/codeql-action/analyze@v2

    # Step 3: Process sensitive data if detected
    - name: Detect sensitive files
      id: detect_sensitive_files
      run: |
        # List of files to check for sensitive data
        SENSITIVE_FILES=".env config/private.key config/secrets.json"
        
        # Detect any files matching these patterns
        DETECTED_FILES=""
        for file in $SENSITIVE_FILES; do
          if [[ -f "$file" ]]; then
            DETECTED_FILES+="$file "
          fi
        done

        # Set the output for detected files
        echo "::set-output name=files::$DETECTED_FILES"

    # Step 4: Encrypt sensitive files
    - name: Encrypt detected sensitive files
      if: steps.detect_sensitive_files.outputs.files != ''
      run: |
        echo "Sensitive files detected. Running encryption..."
        chmod +x secure_sensitive_data.sh
        ./secure_sensitive_data.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Step 5: Commit encrypted files
    - name: Commit encrypted files
      if: steps.detect_sensitive_files.outputs.files != ''
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .gitignore encrypted_files .encryption_key
        git commit -m "Encrypt sensitive files [auto-generated]"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
